### ISSUE TITLE
Handle different request methods

### ISSUE THREAD

**Issue by nathanjohnson320** [YttriumJS/yttrium-server#2]
right now i think we only handle GET requests, out would be nice to handle POST/PUT/DELETE etc.

Maybe add a child to each route for the type? That might break our current routing though

```
$.route('index')
  .append('<test>')

$.route('test')
  .append('<post>')
  .append('<get>')

$.route('test post')
  .on('route', (e, req, res) => {
    return res.end('Im a post');
  });

$.route('test get')
  .on('route', (e, req, res) => {
    return res.end('Im a get');
  });
```

**Comment by stripedpajamas** [comment]
If anything we'd probably just make it an attribute of the route element. Like data-method or something like that. It sounds like we have most of the pieces to tie things together-- query parser for GET, body parser for POST. Now just need a way to distinguish.

**Comment by stripedpajamas** [comment]
This is done in commit https://github.com/YttriumJS/yttrium-server/commit/011677c3d99e884613b956a029c8dc6dc77ddc26
